In [4]:
import numpy as np
import keras
import keras.backend as K
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from tensorflow.keras.optimizers import SGD
#from matplotlib import pyplot as plt

data = np.asarray([])
data = np.genfromtxt("inputTeachers.csv",delimiter=',')

inputs = data[1:,:7]
outputs = data[1:,7]

print("Inputs : \n",inputs,"\n")

outputs = keras.utils.np_utils.to_categorical(outputs)
print("Outputs : \n",outputs,"\n")

#    Je prépare ma descente du gradient avec un learning rate à 0.1 -> 0.9 
sgd = SGD(lr=10)

#    Mon modèle est de type séquentiel. Cela veut dire que les couches (layers) du réseau de neurones se suivent les unes après les autres
model = Sequential()
#    J'ajoute une couche à mon modèle. J'indique que cette couche a une taille d'input de 7, et une taille d'output de 10
model.add(Dense(10, input_dim=7, activation='softmax'))

#   J'affiche une représentation du modèle
model.summary()

#   Je compile le modèle avec la descente du gradient et une losse de type (t-y)² (celle vu en cours)
model.compile(optimizer=sgd, loss='mean_squared_error')
#   Je lance l'apprentissage du modèle sur 500 epochs -> 1000 epochs -> 2000 epochs(si errone)
history = model.fit(inputs, outputs, epochs=2000)

#   Ajout d'un input eronne sur le 4
inputsErrone = np.array([0,1,1,0,0,1,0])
inputs = np.r_[inputs,[inputsErrone]]
print("\n",inputs)

#   Voyons voir si notre réseau de neurones a bien appris !
predictions = model.predict(inputs)
print("\n",np.argmax(predictions,1))

print(history.history.keys())
# Affichage 

#plt.plot(history.history['loss'])
#plt.plot(history.history['val_loss'])
#plt.title('model loss')
#plt.ylabel('loss')
#plt.xlabel('epoch')
#plt.legend(['train', 'val'], loc='upper left')
#plt.show()

Inputs : 
 [[1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1.]
 [1. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1.]] 

Outputs : 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] 

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                80        
                                                                 
Total params: 80
Trainable params: 80
Non-trainable params: 0
_____________________________________________________

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


1/1 [==============================] - 0s 221ms/step - loss: 0.0962
Epoch 2/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.0947
Epoch 3/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.0935
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.0926
Epoch 5/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0917
Epoch 6/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0909
Epoch 7/2000
1/1 [==============================] - 0s 8ms/step - loss: 0.0902
Epoch 8/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0895
Epoch 9/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0888
Epoch 10/2000
1/1 [==============================] - 0s 6ms/step - loss: 0.0882
Epoch 11/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.0875
Epoch 12/2000
1/1 [==============================] - 0s 5ms/step - loss: 0.0869
Epoch 13/2000
1/1 [==============================] - 0s 9ms/